# Generated by Django 3.2.5 on 2021-07-09 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transitions',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('priority', models.DecimalField(decimal_places=4, max_digits=5)),
                ('name', models.CharField(max_length=200)),
                ('filename', models.FileField(upload_to='assets/transitions/files')),
                ('thumbnail', models.FileField(upload_to='assets/transitions/thumbnail')),
            ],
            options={
                'db_table': 'transitions',
            },
        ),
    ]
