# Generated by Django 3.2.5 on 2021-07-09 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reactions',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('priority', models.DecimalField(decimal_places=4, max_digits=5)),
                ('name', models.CharField(max_length=200)),
                ('filename', models.FileField(upload_to='assets/reactions/files')),
                ('thumbnail', models.FileField(upload_to='assets/reactions/thumbnail')),
            ],
            options={
                'db_table': 'reactions',
            },
        ),
    ]
