# Generated by Django 3.2.5 on 2021-07-09 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_reactions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('priority', models.DecimalField(decimal_places=4, max_digits=5)),
                ('name', models.CharField(max_length=200)),
                ('filename', models.FileField(upload_to='assets/music/files')),
                ('thumbnail', models.FileField(upload_to='assets/music/thumbnail')),
                ('type', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'music',
            },
        ),
    ]
