# Generated by Django 3.2.5 on 2021-07-09 20:47

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_music'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='filename',
            field=models.FileField(upload_to=app.models.Music.get_filename_path),
        ),
        migrations.AlterField(
            model_name='music',
            name='thumbnail',
            field=models.FileField(upload_to=app.models.Music.get_thumbnail_path),
        ),
    ]
